name: Publish Container Images

on:
  push:
    tags:
      - '20[0-9][0-9]-[01][0-9]-[0-3][0-9]'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [mopidy, radicale, snapcast-server]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: ghcr.io registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
